### ISSUE TITLE
Not able to run tests

### ISSUE THREAD

**Issue by sangeeta0201** [SaswatPadhi/PIE#11]
Hello,

I m trying to build your system and run tests but, I am not able to do that.

I have installed all libraries as mentioned and running tests -

```
  ./test_all.sh

 ############ CG_SIZE = 2 16 all ############

./test_all.sh: line 16: ../logs/$CGROUP/$FIX_TESTS/pie/$CG_SIZE/specs/list/RESULT: ambiguous redirect
Scanning line 513 ... DONE
File "testGen.ml", line 2, characters 5-21:
Error: Unbound module QCheck.Arbitrary
makefile:4: recipe for target 'dep-only' failed
make: *** [dep-only] Error 2
File "Tlist.ml", line 2, characters 5-21:
Error: Unbound module QCheck.Arbitrary
File "_none_", line 1:
Error: Cannot find file Tlist.cmx
Scanning line 513 ... DONE
```

**Comment by SaswatPadhi** [comment]
Thanks for the report.

The build is currently broken because `QCheck` introduced a breaking change to their API.
Please try pinning `QCheck` at version 0.4: `opam pin qcheck 0.4` and try building again.

**Comment by sangeeta0201** [comment]
Thank you Saswat. It worked.

**Comment by SaswatPadhi** [comment]
Glad it worked for you!
